// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// check_na_vector_cpp
List check_na_vector_cpp(SEXP x);
RcppExport SEXP _SigBridgeR_check_na_vector_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(check_na_vector_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// check_na_dense2d_cpp
List check_na_dense2d_cpp(SEXP x, IntegerVector dim);
RcppExport SEXP _SigBridgeR_check_na_dense2d_cpp(SEXP xSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(check_na_dense2d_cpp(x, dim));
    return rcpp_result_gen;
END_RCPP
}
// check_na_dataframe_cpp
List check_na_dataframe_cpp(List df, int nr);
RcppExport SEXP _SigBridgeR_check_na_dataframe_cpp(SEXP dfSEXP, SEXP nrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type nr(nrSEXP);
    rcpp_result_gen = Rcpp::wrap(check_na_dataframe_cpp(df, nr));
    return rcpp_result_gen;
END_RCPP
}
// check_na_sparse_csc_cpp
List check_na_sparse_csc_cpp(SEXP x, IntegerVector i, IntegerVector p, IntegerVector dim);
RcppExport SEXP _SigBridgeR_check_na_sparse_csc_cpp(SEXP xSEXP, SEXP iSEXP, SEXP pSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(check_na_sparse_csc_cpp(x, i, p, dim));
    return rcpp_result_gen;
END_RCPP
}
// check_na_sparse_triplet_cpp
List check_na_sparse_triplet_cpp(SEXP x, IntegerVector i, IntegerVector j, IntegerVector dim);
RcppExport SEXP _SigBridgeR_check_na_sparse_triplet_cpp(SEXP xSEXP, SEXP iSEXP, SEXP jSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(check_na_sparse_triplet_cpp(x, i, j, dim));
    return rcpp_result_gen;
END_RCPP
}
// CountsToTPM_impl
SEXP CountsToTPM_impl(SEXP counts, NumericVector gene_length);
RcppExport SEXP _SigBridgeR_CountsToTPM_impl(SEXP countsSEXP, SEXP gene_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gene_length(gene_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(CountsToTPM_impl(counts, gene_length));
    return rcpp_result_gen;
END_RCPP
}
// IsSkewedDynamic_cpp
LogicalVector IsSkewedDynamic_cpp(SEXP x, double target, double expected_p, int n_sd);
RcppExport SEXP _SigBridgeR_IsSkewedDynamic_cpp(SEXP xSEXP, SEXP targetSEXP, SEXP expected_pSEXP, SEXP n_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type expected_p(expected_pSEXP);
    Rcpp::traits::input_parameter< int >::type n_sd(n_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(IsSkewedDynamic_cpp(x, target, expected_p, n_sd));
    return rcpp_result_gen;
END_RCPP
}
// find_diff_in_2_lists
SEXP find_diff_in_2_lists(SEXP x, SEXP y);
RcppExport SEXP _SigBridgeR_find_diff_in_2_lists(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(find_diff_in_2_lists(x, y));
    return rcpp_result_gen;
END_RCPP
}
// make_null_list_NULL
SEXP make_null_list_NULL(SEXP x);
RcppExport SEXP _SigBridgeR_make_null_list_NULL(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(make_null_list_NULL(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_assign_plan
void fast_assign_plan(List plan, SEXP rhs, Environment env);
RcppExport SEXP _SigBridgeR_fast_assign_plan(SEXP planSEXP, SEXP rhsSEXP, SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type plan(planSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< Environment >::type env(envSEXP);
    fast_assign_plan(plan, rhs, env);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SigBridgeR_check_na_vector_cpp", (DL_FUNC) &_SigBridgeR_check_na_vector_cpp, 1},
    {"_SigBridgeR_check_na_dense2d_cpp", (DL_FUNC) &_SigBridgeR_check_na_dense2d_cpp, 2},
    {"_SigBridgeR_check_na_dataframe_cpp", (DL_FUNC) &_SigBridgeR_check_na_dataframe_cpp, 2},
    {"_SigBridgeR_check_na_sparse_csc_cpp", (DL_FUNC) &_SigBridgeR_check_na_sparse_csc_cpp, 4},
    {"_SigBridgeR_check_na_sparse_triplet_cpp", (DL_FUNC) &_SigBridgeR_check_na_sparse_triplet_cpp, 4},
    {"_SigBridgeR_CountsToTPM_impl", (DL_FUNC) &_SigBridgeR_CountsToTPM_impl, 2},
    {"_SigBridgeR_IsSkewedDynamic_cpp", (DL_FUNC) &_SigBridgeR_IsSkewedDynamic_cpp, 4},
    {"_SigBridgeR_find_diff_in_2_lists", (DL_FUNC) &_SigBridgeR_find_diff_in_2_lists, 2},
    {"_SigBridgeR_make_null_list_NULL", (DL_FUNC) &_SigBridgeR_make_null_list_NULL, 1},
    {"_SigBridgeR_fast_assign_plan", (DL_FUNC) &_SigBridgeR_fast_assign_plan, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SigBridgeR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
