// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aggregate_dup_cols_cpp
NumericMatrix aggregate_dup_cols_cpp(NumericMatrix x, CharacterVector col_names, std::string method);
RcppExport SEXP _SigBridgeR_aggregate_dup_cols_cpp(SEXP xSEXP, SEXP col_namesSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type col_names(col_namesSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(aggregate_dup_cols_cpp(x, col_names, method));
    return rcpp_result_gen;
END_RCPP
}
// aggregate_dup_rows_cpp
NumericMatrix aggregate_dup_rows_cpp(NumericMatrix x, CharacterVector row_names, std::string method);
RcppExport SEXP _SigBridgeR_aggregate_dup_rows_cpp(SEXP xSEXP, SEXP row_namesSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type row_names(row_namesSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(aggregate_dup_rows_cpp(x, row_names, method));
    return rcpp_result_gen;
END_RCPP
}
// check_na_vector_cpp
List check_na_vector_cpp(SEXP x);
RcppExport SEXP _SigBridgeR_check_na_vector_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(check_na_vector_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// check_na_dense2d_cpp
List check_na_dense2d_cpp(SEXP x, IntegerVector dim);
RcppExport SEXP _SigBridgeR_check_na_dense2d_cpp(SEXP xSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(check_na_dense2d_cpp(x, dim));
    return rcpp_result_gen;
END_RCPP
}
// check_na_dataframe_cpp
List check_na_dataframe_cpp(List df, int nr);
RcppExport SEXP _SigBridgeR_check_na_dataframe_cpp(SEXP dfSEXP, SEXP nrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type nr(nrSEXP);
    rcpp_result_gen = Rcpp::wrap(check_na_dataframe_cpp(df, nr));
    return rcpp_result_gen;
END_RCPP
}
// check_na_sparse_csc_cpp
List check_na_sparse_csc_cpp(SEXP x, IntegerVector i, IntegerVector p, IntegerVector dim);
RcppExport SEXP _SigBridgeR_check_na_sparse_csc_cpp(SEXP xSEXP, SEXP iSEXP, SEXP pSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(check_na_sparse_csc_cpp(x, i, p, dim));
    return rcpp_result_gen;
END_RCPP
}
// check_na_sparse_triplet_cpp
List check_na_sparse_triplet_cpp(SEXP x, IntegerVector i, IntegerVector j, IntegerVector dim);
RcppExport SEXP _SigBridgeR_check_na_sparse_triplet_cpp(SEXP xSEXP, SEXP iSEXP, SEXP jSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(check_na_sparse_triplet_cpp(x, i, j, dim));
    return rcpp_result_gen;
END_RCPP
}
// CountsToTPM_impl
SEXP CountsToTPM_impl(SEXP counts, NumericVector gene_length);
RcppExport SEXP _SigBridgeR_CountsToTPM_impl(SEXP countsSEXP, SEXP gene_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gene_length(gene_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(CountsToTPM_impl(counts, gene_length));
    return rcpp_result_gen;
END_RCPP
}
// get_bulk_hvg
Rcpp::CharacterVector get_bulk_hvg(const arma::mat& patdata, const Rcpp::CharacterVector& common_genes, const int n_hvg);
RcppExport SEXP _SigBridgeR_get_bulk_hvg(SEXP patdataSEXP, SEXP common_genesSEXP, SEXP n_hvgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type patdata(patdataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type common_genes(common_genesSEXP);
    Rcpp::traits::input_parameter< const int >::type n_hvg(n_hvgSEXP);
    rcpp_result_gen = Rcpp::wrap(get_bulk_hvg(patdata, common_genes, n_hvg));
    return rcpp_result_gen;
END_RCPP
}
// normFunc_ptr
arma::vec normFunc_ptr(const arma::vec& x);
RcppExport SEXP _SigBridgeR_normFunc_ptr(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(normFunc_ptr(x));
    return rcpp_result_gen;
END_RCPP
}
// scaleFunc_ptr
arma::vec scaleFunc_ptr(const arma::vec& x);
RcppExport SEXP _SigBridgeR_scaleFunc_ptr(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleFunc_ptr(x));
    return rcpp_result_gen;
END_RCPP
}
// normalizeScale_ptr
arma::mat normalizeScale_ptr(const arma::mat& X);
RcppExport SEXP _SigBridgeR_normalizeScale_ptr(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(normalizeScale_ptr(X));
    return rcpp_result_gen;
END_RCPP
}
// preprocessCounts_ptr
arma::mat preprocessCounts_ptr(const arma::mat& X);
RcppExport SEXP _SigBridgeR_preprocessCounts_ptr(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(preprocessCounts_ptr(X));
    return rcpp_result_gen;
END_RCPP
}
// ExtractMetricsCpp
List ExtractMetricsCpp(SEXP assay_data, SEXP counts, double low_expressed_thresh);
RcppExport SEXP _SigBridgeR_ExtractMetricsCpp(SEXP assay_dataSEXP, SEXP countsSEXP, SEXP low_expressed_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type assay_data(assay_dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type low_expressed_thresh(low_expressed_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(ExtractMetricsCpp(assay_data, counts, low_expressed_thresh));
    return rcpp_result_gen;
END_RCPP
}
// IsCountsMatrixImpl
bool IsCountsMatrixImpl(const arma::mat& x, bool verbose, double integer_tol, double min_integer_fraction);
RcppExport SEXP _SigBridgeR_IsCountsMatrixImpl(SEXP xSEXP, SEXP verboseSEXP, SEXP integer_tolSEXP, SEXP min_integer_fractionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< double >::type integer_tol(integer_tolSEXP);
    Rcpp::traits::input_parameter< double >::type min_integer_fraction(min_integer_fractionSEXP);
    rcpp_result_gen = Rcpp::wrap(IsCountsMatrixImpl(x, verbose, integer_tol, min_integer_fraction));
    return rcpp_result_gen;
END_RCPP
}
// weighted_vote_cpp
CharacterVector weighted_vote_cpp(CharacterMatrix vote_data, NumericVector weights, int ties_method);
RcppExport SEXP _SigBridgeR_weighted_vote_cpp(SEXP vote_dataSEXP, SEXP weightsSEXP, SEXP ties_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type vote_data(vote_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type ties_method(ties_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_vote_cpp(vote_data, weights, ties_method));
    return rcpp_result_gen;
END_RCPP
}
// find_diff_in_2_lists
SEXP find_diff_in_2_lists(SEXP x, SEXP y);
RcppExport SEXP _SigBridgeR_find_diff_in_2_lists(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(find_diff_in_2_lists(x, y));
    return rcpp_result_gen;
END_RCPP
}
// IsSkewedDynamic_cpp
LogicalVector IsSkewedDynamic_cpp(SEXP x, double target, double expected_p, int n_sd);
RcppExport SEXP _SigBridgeR_IsSkewedDynamic_cpp(SEXP xSEXP, SEXP targetSEXP, SEXP expected_pSEXP, SEXP n_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type expected_p(expected_pSEXP);
    Rcpp::traits::input_parameter< int >::type n_sd(n_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(IsSkewedDynamic_cpp(x, target, expected_p, n_sd));
    return rcpp_result_gen;
END_RCPP
}
// list_to_character_recursive
std::string list_to_character_recursive(List x);
RcppExport SEXP _SigBridgeR_list_to_character_recursive(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(list_to_character_recursive(x));
    return rcpp_result_gen;
END_RCPP
}
// make_null_list_NULL
SEXP make_null_list_NULL(SEXP x);
RcppExport SEXP _SigBridgeR_make_null_list_NULL(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(make_null_list_NULL(x));
    return rcpp_result_gen;
END_RCPP
}
// normalize_metric
NumericVector normalize_metric(NumericVector x, bool invert);
RcppExport SEXP _SigBridgeR_normalize_metric(SEXP xSEXP, SEXP invertSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type invert(invertSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_metric(x, invert));
    return rcpp_result_gen;
END_RCPP
}
// fast_assign_plan
void fast_assign_plan(List plan, SEXP rhs, Environment env);
RcppExport SEXP _SigBridgeR_fast_assign_plan(SEXP planSEXP, SEXP rhsSEXP, SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type plan(planSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< Environment >::type env(envSEXP);
    fast_assign_plan(plan, rhs, env);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SigBridgeR_aggregate_dup_cols_cpp", (DL_FUNC) &_SigBridgeR_aggregate_dup_cols_cpp, 3},
    {"_SigBridgeR_aggregate_dup_rows_cpp", (DL_FUNC) &_SigBridgeR_aggregate_dup_rows_cpp, 3},
    {"_SigBridgeR_check_na_vector_cpp", (DL_FUNC) &_SigBridgeR_check_na_vector_cpp, 1},
    {"_SigBridgeR_check_na_dense2d_cpp", (DL_FUNC) &_SigBridgeR_check_na_dense2d_cpp, 2},
    {"_SigBridgeR_check_na_dataframe_cpp", (DL_FUNC) &_SigBridgeR_check_na_dataframe_cpp, 2},
    {"_SigBridgeR_check_na_sparse_csc_cpp", (DL_FUNC) &_SigBridgeR_check_na_sparse_csc_cpp, 4},
    {"_SigBridgeR_check_na_sparse_triplet_cpp", (DL_FUNC) &_SigBridgeR_check_na_sparse_triplet_cpp, 4},
    {"_SigBridgeR_CountsToTPM_impl", (DL_FUNC) &_SigBridgeR_CountsToTPM_impl, 2},
    {"_SigBridgeR_get_bulk_hvg", (DL_FUNC) &_SigBridgeR_get_bulk_hvg, 3},
    {"_SigBridgeR_normFunc_ptr", (DL_FUNC) &_SigBridgeR_normFunc_ptr, 1},
    {"_SigBridgeR_scaleFunc_ptr", (DL_FUNC) &_SigBridgeR_scaleFunc_ptr, 1},
    {"_SigBridgeR_normalizeScale_ptr", (DL_FUNC) &_SigBridgeR_normalizeScale_ptr, 1},
    {"_SigBridgeR_preprocessCounts_ptr", (DL_FUNC) &_SigBridgeR_preprocessCounts_ptr, 1},
    {"_SigBridgeR_ExtractMetricsCpp", (DL_FUNC) &_SigBridgeR_ExtractMetricsCpp, 3},
    {"_SigBridgeR_IsCountsMatrixImpl", (DL_FUNC) &_SigBridgeR_IsCountsMatrixImpl, 4},
    {"_SigBridgeR_weighted_vote_cpp", (DL_FUNC) &_SigBridgeR_weighted_vote_cpp, 3},
    {"_SigBridgeR_find_diff_in_2_lists", (DL_FUNC) &_SigBridgeR_find_diff_in_2_lists, 2},
    {"_SigBridgeR_IsSkewedDynamic_cpp", (DL_FUNC) &_SigBridgeR_IsSkewedDynamic_cpp, 4},
    {"_SigBridgeR_list_to_character_recursive", (DL_FUNC) &_SigBridgeR_list_to_character_recursive, 1},
    {"_SigBridgeR_make_null_list_NULL", (DL_FUNC) &_SigBridgeR_make_null_list_NULL, 1},
    {"_SigBridgeR_normalize_metric", (DL_FUNC) &_SigBridgeR_normalize_metric, 2},
    {"_SigBridgeR_fast_assign_plan", (DL_FUNC) &_SigBridgeR_fast_assign_plan, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SigBridgeR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
