# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_na_vector_cpp <- function(x) {
    .Call(`_SigBridgeR_check_na_vector_cpp`, x)
}

check_na_dense2d_cpp <- function(x, dim) {
    .Call(`_SigBridgeR_check_na_dense2d_cpp`, x, dim)
}

check_na_dataframe_cpp <- function(df, nr) {
    .Call(`_SigBridgeR_check_na_dataframe_cpp`, df, nr)
}

check_na_sparse_csc_cpp <- function(x, i, p, dim) {
    .Call(`_SigBridgeR_check_na_sparse_csc_cpp`, x, i, p, dim)
}

check_na_sparse_triplet_cpp <- function(x, i, j, dim) {
    .Call(`_SigBridgeR_check_na_sparse_triplet_cpp`, x, i, j, dim)
}

CountsToTPM_impl <- function(counts, gene_length) {
    .Call(`_SigBridgeR_CountsToTPM_impl`, counts, gene_length)
}

IsSkewedDynamic_cpp <- function(x, target = 0.0, expected_p = 0.8, n_sd = 4L) {
    .Call(`_SigBridgeR_IsSkewedDynamic_cpp`, x, target, expected_p, n_sd)
}

find_diff_in_2_lists <- function(x, y) {
    .Call(`_SigBridgeR_find_diff_in_2_lists`, x, y)
}

make_null_list_NULL <- function(x) {
    .Call(`_SigBridgeR_make_null_list_NULL`, x)
}

fast_assign_plan <- function(plan, rhs, env) {
    invisible(.Call(`_SigBridgeR_fast_assign_plan`, plan, rhs, env))
}

