# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregate_dup_cols_cpp <- function(initialized_matrix, col_names, method) {
    .Call(`_SigBridgeR_aggregate_dup_cols_cpp`, initialized_matrix, col_names, method)
}

aggregate_dup_rows_cpp <- function(initialized_matrix, row_names, method) {
    .Call(`_SigBridgeR_aggregate_dup_rows_cpp`, initialized_matrix, row_names, method)
}

check_na_beachmat_matrix_cpp <- function(initialized_matrix) {
    .Call(`_SigBridgeR_check_na_beachmat_matrix_cpp`, initialized_matrix)
}

check_na_vector_cpp <- function(x) {
    .Call(`_SigBridgeR_check_na_vector_cpp`, x)
}

check_na_dataframe_cpp <- function(df, nr) {
    .Call(`_SigBridgeR_check_na_dataframe_cpp`, df, nr)
}

counts_to_tpm_cpp <- function(initialized_counts, row_names, gene_length) {
    .Call(`_SigBridgeR_counts_to_tpm_cpp`, initialized_counts, row_names, gene_length)
}

get_bulk_hvg <- function(patdata, common_genes, n_hvg) {
    .Call(`_SigBridgeR_get_bulk_hvg`, patdata, common_genes, n_hvg)
}

normFunc_ptr <- function(x) {
    .Call(`_SigBridgeR_normFunc_ptr`, x)
}

scaleFunc_ptr <- function(x) {
    .Call(`_SigBridgeR_scaleFunc_ptr`, x)
}

normalizeScale_ptr <- function(X) {
    .Call(`_SigBridgeR_normalizeScale_ptr`, X)
}

preprocessCounts_ptr <- function(X) {
    .Call(`_SigBridgeR_preprocessCounts_ptr`, X)
}

ExtractMetricsCpp <- function(assay_data, counts, low_expressed_thresh = 0.2) {
    .Call(`_SigBridgeR_ExtractMetricsCpp`, assay_data, counts, low_expressed_thresh)
}

fpkm_to_tpm_cpp <- function(initialized_fpkm, na_as_zero = TRUE, verbose = TRUE) {
    .Call(`_SigBridgeR_fpkm_to_tpm_cpp`, initialized_fpkm, na_as_zero, verbose)
}

gtf_file_to_gene_length <- function(path, verbose = TRUE, canonical_chr_only = FALSE) {
    .Call(`_SigBridgeR_gtf_file_to_gene_length`, path, verbose, canonical_chr_only)
}

r_gtf_lines_to_gene_length <- function(lines, verbose = TRUE, canonical_chr_only = FALSE) {
    .Call(`_SigBridgeR_r_gtf_lines_to_gene_length`, lines, verbose, canonical_chr_only)
}

is_counts_matrix_cpp <- function(initialized_matrix, verbose = FALSE, integer_tol = 1e-8, min_integer_fraction = 0.95) {
    .Call(`_SigBridgeR_is_counts_matrix_cpp`, initialized_matrix, verbose, integer_tol, min_integer_fraction)
}

weighted_vote_cpp <- function(vote_data, weights, ties_method) {
    .Call(`_SigBridgeR_weighted_vote_cpp`, vote_data, weights, ties_method)
}

find_diff_in_2_lists <- function(x, y) {
    .Call(`_SigBridgeR_find_diff_in_2_lists`, x, y)
}

IsSkewedDynamic_cpp <- function(x, target = 0.0, expected_p = 0.8, n_sd = 4L) {
    .Call(`_SigBridgeR_IsSkewedDynamic_cpp`, x, target, expected_p, n_sd)
}

list_to_character_recursive <- function(x) {
    .Call(`_SigBridgeR_list_to_character_recursive`, x)
}

make_null_list_NULL <- function(x) {
    .Call(`_SigBridgeR_make_null_list_NULL`, x)
}

normalize_metric <- function(x, invert = FALSE) {
    .Call(`_SigBridgeR_normalize_metric`, x, invert)
}

fast_assign_plan <- function(plan, rhs, env) {
    invisible(.Call(`_SigBridgeR_fast_assign_plan`, plan, rhs, env))
}

